name: CI

on:
  schedule:
    - cron:  '*/60 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo " " >> README.md
          git config user.name edwardjlsh
          git config user.email edwardjlsh@icloud.com
          git add .
          git commit -m "Always green!"
          git push
